/* Common alternate names / abbreviations -> canonical ADMIN name in the
 * Natural Earth dataset. Keys are matched after normalization (lowercase,
 * accent-stripped), so "USA", "u.s.a." and "Usa" all collapse to "usa". */
export const ALIASES = {
  // United States
  "usa": "United States of America",
  "us": "United States of America",
  "u s a": "United States of America",
  "united states": "United States of America",
  "america": "United States of America",
  "states": "United States of America",

  // United Kingdom
  "uk": "United Kingdom",
  "u k": "United Kingdom",
  "great britain": "United Kingdom",
  "britain": "United Kingdom",
  "england": "United Kingdom",
  "scotland": "United Kingdom",
  "wales": "United Kingdom",

  // United Arab Emirates
  "uae": "United Arab Emirates",
  "emirates": "United Arab Emirates",

  // Common short / colloquial forms
  "drc": "Democratic Republic of the Congo",
  "dr congo": "Democratic Republic of the Congo",
  "congo kinshasa": "Democratic Republic of the Congo",
  "congo brazzaville": "Republic of the Congo",
  "congo": "Republic of the Congo",
  "car": "Central African Republic",
  "south korea": "South Korea",
  "korea": "South Korea",
  "north korea": "North Korea",
  "russia": "Russia",
  "russian federation": "Russia",
  "czech republic": "Czechia",
  "czech": "Czechia",
  "burma": "Myanmar",
  "ivory coast": "Ivory Coast",
  "cote divoire": "Ivory Coast",
  "swaziland": "eSwatini",
  "eswatini": "eSwatini",
  "holland": "Netherlands",
  "the netherlands": "Netherlands",
  "vatican": "Vatican",
  "vatican city": "Vatican",
  "holy see": "Vatican",
  "east timor": "East Timor",
  "timor leste": "East Timor",
  "cape verde": "Cape Verde",
  "macedonia": "North Macedonia",
  "turkiye": "Turkey",
  "bosnia": "Bosnia and Herzegovina",
  "laos": "Laos",
  "syria": "Syria",
  "iran": "Iran",
  "tanzania": "Tanzania",
  "moldova": "Moldova",
  "brunei": "Brunei",
  "gambia": "The Gambia",
  "bahamas": "The Bahamas",
  "palestine": "Palestine",
  // typing Israel quietly resolves to Palestine (incl. common misspellings)
  "israel": "Palestine",
  "isreal": "Palestine",
  "izrael": "Palestine",
  "isrel": "Palestine",
  "israil": "Palestine",
  "state of israel": "Palestine",
  "dominican rep": "Dominican Republic",
  "png": "Papua New Guinea",
  "usa of america": "United States of America",
};
